import os
from reportlab.pdfgen import canvas
from pptx import Presentation
from docx import Document

# Create sample_docs directory if not exists
os.makedirs("sample_docs_real", exist_ok=True)

def generate_pdf():
    print("Generating genuine PDF...")
    c = canvas.Canvas("sample_docs_real/fact.pdf")
    c.drawString(100, 750, "CONFIDENTIAL DOCUMENT")
    c.drawString(100, 700, "The secret code for PDF is 1234.")
    c.drawString(100, 650, "This is a genuine PDF file generated by ReportLab.")
    c.save()

def generate_docx():
    print("Generating genuine DOCX...")
    doc = Document()
    doc.add_heading('Confidential Document', 0)
    doc.add_paragraph('The secret code for DOCX is 5678.')
    doc.add_paragraph('This is a genuine DOCX file generated by python-docx.')
    doc.save("sample_docs_real/fact.docx")

def generate_pptx():
    print("Generating genuine PPTX...")
    prs = Presentation()
    slide_layout = prs.slide_layouts[0] # Title Slide
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Confidential Presentation"
    subtitle.text = "The secret code for PPTX is 9012."
    prs.save("sample_docs_real/fact.pptx")

def generate_txt():
    print("Generating genuine TXT...")
    with open("sample_docs_real/fact.txt", "w") as f:
        f.write("CONFIDENTIAL DOCUMENT\n")
        f.write("The secret code for TXT is 3456.\n")
        f.write("This is a genuine text file.\n")

if __name__ == "__main__":
    generate_pdf()
    generate_docx()
    generate_pptx()
    generate_txt()
    print("All genuine samples generated in sample_docs_real/")
